import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'background':                '#f9f9fe',
        'surface':                   '#f9f9fe',
        'surface-bright':            '#f9f9fe',
        'surface-dim':               '#d9dade',
        'surface-variant':           '#e2e2e7',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f3f3f8',
        'surface-container':         '#ededf2',
        'surface-container-high':    '#e8e8ed',
        'surface-container-highest': '#e2e2e7',
        'on-surface':                '#1a1c1f',
        'on-surface-variant':        '#444748',
        'inverse-surface':           '#2e3034',
        'inverse-on-surface':        '#f0f0f5',
        'outline':                   '#747878',
        'outline-variant':           '#c4c7c7',
        'primary':                   '#000000',
        'on-primary':                '#ffffff',
        'primary-container':         '#1c1b1b',
        'on-primary-container':      '#858383',
        'primary-fixed':             '#e5e2e1',
        'primary-fixed-dim':         '#c8c6c5',
        'inverse-primary':           '#c8c6c5',
        'secondary':                 '#5d5f5f',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#dfe0e0',
        'on-secondary-container':    '#616363',
        'tertiary':                  '#000000',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#1a1b1f',
        'on-tertiary-container':     '#838388',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'on-background':             '#1a1c1f',
        'surface-tint':              '#5f5e5e',
      },
      fontFamily: {
        'display-lg':         ['"Hanken Grotesk"', 'sans-serif'],
        'headline-xl':        ['"Hanken Grotesk"', 'sans-serif'],
        'headline-xl-mobile': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md':        ['"Hanken Grotesk"', 'sans-serif'],
        'label-sm':           ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg':            ['Inter', 'sans-serif'],
        'body-md':            ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':         ['80px', { lineHeight: '88px',  letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-xl':        ['48px', { lineHeight: '52px',  letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-xl-mobile': ['36px', { lineHeight: '40px',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md':        ['32px', { lineHeight: '38px',  letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'label-sm':           ['13px', { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg':      '0.5rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      spacing: {
        'margin-desktop':      '64px',
        'margin-mobile':       '20px',
        'gutter':              '16px',
        'unit':                '8px',
        'container-max-width': '1440px',
      },
    },
  },
} satisfies Config
